const userConstants = {
    SET_USERNAME: 'SET_USERNAME',
    SET_LASTNAME: 'SET_LASTNAME',
    SET_THIRDNAME: 'SET_THIRDNAME',
    SET_EMAIL: 'SET_EMAIL',
    SET_PHONE: 'SET_PHONE',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_PASSWORD2: 'SET_PASSWORD2',
    SET_GENDER: 'SET_GENDER',
    SET_IS_LOGGED: 'SET_IS_LOGGED',
    LOGIN_USER: 'LOGIN_USER',
    SET_IS_LOGGED_OUT: 'SET_IS_LOGGED_OUT',
    SET_SMS_CODE: 'SET_SMS_CODE',
}

export default userConstants;